/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;

import Model.EcoSystem;
import Model.Enterprises.Hospital;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author viralsuchak
 */
public class HospitalAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkArea
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Hospital hospitalEnterprise;
    UserAccount userAccount;
  
    
    public HospitalAdminWorkArea(JPanel container, EcoSystem system) {
        initComponents();
        this.userProcessContainer=container;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userprocesscontainer = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        hospCmbBox = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospAdmin = new javax.swing.JTable();

        userprocesscontainer.setMinimumSize(new java.awt.Dimension(1000, 1000));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");

        hospCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctors", "Lab Technicians", "Front Desk Assistant" }));
        hospCmbBox.setMaximumSize(new java.awt.Dimension(200, 50));
        hospCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospCmbBoxActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        tblHospAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospAdmin);

        javax.swing.GroupLayout userprocesscontainerLayout = new javax.swing.GroupLayout(userprocesscontainer);
        userprocesscontainer.setLayout(userprocesscontainerLayout);
        userprocesscontainerLayout.setHorizontalGroup(
            userprocesscontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userprocesscontainerLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(userprocesscontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userprocesscontainerLayout.createSequentialGroup()
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hospCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        userprocesscontainerLayout.setVerticalGroup(
            userprocesscontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userprocesscontainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hospCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(userprocesscontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userprocesscontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userprocesscontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hospCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospCmbBoxActionPerformed
        hospCmbBox.addItem("Doctors");
        hospCmbBox.addItem("Lab Technicians");
        hospCmbBox.addItem("Front Desk Assistants");
    }//GEN-LAST:event_hospCmbBoxActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if (hospCmbBox.getSelectedItem().equals("Doctors")) {
            
           DoctorWorkAreaJPanel ddjp = new DoctorWorkAreaJPanel(userprocesscontainer,hospitalEnterprise, userAccount, ecosystem);
           userprocesscontainer.add("DoctorDetailsJPanel",ddjp);

           CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
           layout.next(userprocesscontainer);
        }
       
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> hospCmbBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHospAdmin;
    private javax.swing.JPanel userprocesscontainer;
    // End of variables declaration//GEN-END:variables
}
