/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;

import java.awt.CardLayout;

/**
 *
 * @author viralsuchak
 */
public class HospitalAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkArea
     */
    public HospitalAdminWorkArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userprocesscontainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospAdmin = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        hospCmbBox = new javax.swing.JComboBox<>();

        userprocesscontainer.setMinimumSize(new java.awt.Dimension(1000, 1000));
        userprocesscontainer.setLayout(new java.awt.CardLayout());

        tblHospAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospAdmin);

        userprocesscontainer.add(jScrollPane1, "card3");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        userprocesscontainer.add(btnView, "card4");

        btnAdd.setText("Add");
        userprocesscontainer.add(btnAdd, "card5");

        btnDelete.setText("Delete");
        userprocesscontainer.add(btnDelete, "card6");

        hospCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hospCmbBox.setMaximumSize(new java.awt.Dimension(200, 50));
        hospCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospCmbBoxActionPerformed(evt);
            }
        });
        userprocesscontainer.add(hospCmbBox, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userprocesscontainer, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(842, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userprocesscontainer, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hospCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospCmbBoxActionPerformed
        hospCmbBox.addItem("Doctors");
        hospCmbBox.addItem("Lab Technicians");
        hospCmbBox.addItem("Front Desk Assistants");
    }//GEN-LAST:event_hospCmbBoxActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
       DoctorDetailsJPanel ddjp = new DoctorDetailsJPanel(userprocesscontainer);
       userprocesscontainer.add("DoctorDetailsJPanel",ddjp);
       
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.show(userprocesscontainer, "DoctorDetails");
       
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> hospCmbBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHospAdmin;
    private javax.swing.JPanel userprocesscontainer;
    // End of variables declaration//GEN-END:variables
}
