/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin;

import javax.swing.JPanel;

/**
 *
 * @author aakrutighatole
 */
public class ViewDetailsHospital extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetails
     */
    JPanel userProcessContainer;
    public ViewDetailsHospital(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        System.out.println("hello");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jLabel1.setText("Organisation Details");
        add(jLabel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
